update

diff --git a/venv b/venv
--- a/venv
+++ b/venv
@@ -1,27 +1,55 @@
 #!/bin/sh
 
-NAME=${1:-$(basename $(pwd))}
-DIR=${2:-${HOME}/venv/${NAME}}
-
-if [ -d ${DIR} ]; then :; else
-  echo "Executing: python3 -m venv ${DIR}"
-  python3 -m venv ${DIR}
+if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+    printf "Usage: %s [directory] [venv name] [venv directory]\n" "$(basename "$0")"
+    exit 0
 fi
 
-if [ -f ${DIR}/bin/python3 ]; then :; else
-  echo "Error: directory exists, but not venv directory"
-  exit 127
+DIR=$(cd "${1:-"$(pwd)"}" || exit 127; pwd)
+NAME=$2
+VENV=$3
+
+if [ -d "$DIR" ]; then :; else
+    printf "Error: directory does not exist\n"
+    exit 127
 fi
 
-echo "Executing: ${DIR}/bin/python3 -m pip install --upgrade pip"
-${DIR}/bin/python3 -m pip install --upgrade pip
+while true; do
+    if [ -f "$DIR"/requirements.txt ]; then
+        if [ -z "$NAME" ]; then
+            NAME=$(basename "$DIR")
+        fi
+        break
+    fi
+    if [ "$DIR" = "/" ]; then
+        if [ -z "$NAME" ]; then
+            NAME=$(basename "$(pwd)")
+        fi
+        break
+    fi
+    DIR=$(dirname "$DIR")
+done
 
-if [ -f requirements.txt ]; then
-  echo "Executing: ${DIR}/bin/python3 -m pip install -r requirements.txt"
-  ${DIR}/bin/python3 -m pip install -r requirements.txt
+if [ -z "$VENV" ]; then
+    VENV="$HOME/venv/$NAME"
 fi
 
-/bin/echo "Next step: source ${DIR}/bin/activate"
+if [ -d "$VENV" ]; then :; else
+    printf "Executing: python3 -m venv %s\n" "$VENV"
+    python3 -m venv "$VENV"
+fi
+
+if [ -f "$VENV"/bin/python3 ]; then :; else
+    printf "Error: directory exists, but not venv directory\n"
+    exit 127
+fi
+
+if [ -f "$DIR"/requirements.txt ]; then
+    printf "Executing: %s/bin/python3 -m pip install -r %s/requirements.txt\n" "$VENV" "$DIR"
+    "$VENV"/bin/python3 -m pip install -r "$DIR"/requirements.txt
+fi
+
+printf "Next step: source %s/bin/activate\n" "$VENV"
 if [ -e /usr/bin/pbcopy ]; then
-  /bin/echo -n "source ${DIR}/bin/activate" | pbcopy
+  printf "source %s/bin/activate" "$VENV" | pbcopy
 fi
